export const questions = [
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the capital of France?",
    correct_answer: "Paris",
    incorrect_answers: ["Berlin", "London", "Madrid"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the largest planet in our solar system?",
    correct_answer: "Jupiter",
    incorrect_answers: ["Earth", "Mars", "Venus"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "Which gas do plants absorb from the atmosphere?",
    correct_answer: "Carbon dioxide",
    incorrect_answers: ["Oxygen", "Nitrogen", "Hydrogen"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "How many continents are there on Earth?",
    correct_answer: "7",
    incorrect_answers: ["5", "6", "8"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the chemical symbol for gold?",
    correct_answer: "Au",
    incorrect_answers: ["Ag", "Cu", "Fe"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the freezing point of water in degrees Celsius?",
    correct_answer: "0",
    incorrect_answers: ["-10", "100", "32"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the largest mammal in the world?",
    correct_answer: "Blue whale",
    incorrect_answers: ["Elephant", "Giraffe", "Hippopotamus"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the capital of Japan?",
    correct_answer: "Tokyo",
    incorrect_answers: ["Kyoto", "Osaka", "Seoul"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "Which gas do plants absorb from the atmosphere?",
    correct_answer: "Carbon dioxide",
    incorrect_answers: ["Oxygen", "Nitrogen", "Hydrogen"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "How many continents are there on Earth?",
    correct_answer: "7",
    incorrect_answers: ["5", "6", "8"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the chemical symbol for gold?",
    correct_answer: "Au",
    incorrect_answers: ["Ag", "Cu", "Fe"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the freezing point of water in degrees Celsius?",
    correct_answer: "0",
    incorrect_answers: ["-10", "100", "32"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the largest mammal in the world?",
    correct_answer: "Blue whale",
    incorrect_answers: ["Elephant", "Giraffe", "Hippopotamus"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the capital of Japan?",
    correct_answer: "Tokyo",
    incorrect_answers: ["Kyoto", "Osaka", "Seoul"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the chemical formula for water?",
    correct_answer: "H2O",
    incorrect_answers: ["CO2", "O2", "CH4"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "Which planet is known as the Red Planet?",
    correct_answer: "Mars",
    incorrect_answers: ["Venus", "Jupiter", "Saturn"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "In which year was the first modern Olympic Games held?",
    correct_answer: "1896",
    incorrect_answers: ["1900", "1904", "1920"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the currency of Brazil?",
    correct_answer: "Brazilian Real",
    incorrect_answers: ["Peso", "Dollar", "Euro"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the chemical formula for oxygen?",
    correct_answer: "O2",
    incorrect_answers: ["CO2", "H2O", "N2"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "Which gas do plants absorb from the atmosphere?",
    correct_answer: "Carbon dioxide",
    incorrect_answers: ["Oxygen", "Nitrogen", "Hydrogen"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "Who wrote the play 'Romeo and Juliet'?",
    correct_answer: "William Shakespeare",
    incorrect_answers: ["Charles Dickens", "Jane Austen", "Mark Twain"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the largest planet in our solar system?",
    correct_answer: "Jupiter",
    incorrect_answers: ["Earth", "Mars", "Venus"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What gas do plants absorb from the atmosphere?",
    correct_answer: "Carbon dioxide",
    incorrect_answers: ["Oxygen", "Nitrogen", "Hydrogen"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the freezing point of water in degrees Celsius?",
    correct_answer: "0",
    incorrect_answers: ["-10", "100", "32"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the capital of Japan?",
    correct_answer: "Tokyo",
    incorrect_answers: ["Kyoto", "Osaka", "Seoul"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question: "What is the chemical formula for water?",
    correct_answer: "H2O",
    incorrect_answers: ["CO2", "O2", "CH4"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question: "Which planet is known as the Red Planet?",
    correct_answer: "Mars",
    incorrect_answers: ["Venus", "Jupiter", "Saturn"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question: "In which year was the first modern Olympic Games held?",
    correct_answer: "1896",
    incorrect_answers: ["1900", "1904", "1920"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question: "What is the currency of Brazil?",
    correct_answer: "Brazilian Real",
    incorrect_answers: ["Peso", "Dollar", "Euro"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "hard",
    question: "What is the chemical formula for oxygen?",
    correct_answer: "O2",
    incorrect_answers: ["CO2", "H2O", "N2"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "easy",
    question: "What is the chemical symbol for gold?",
    correct_answer: "Au",
    incorrect_answers: ["Ag", "Cu", "Fe"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "easy",
    question: "What is the freezing point of water in degrees Celsius?",
    correct_answer: "0",
    incorrect_answers: ["-10", "100", "32"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "easy",
    question: "What is the largest mammal in the world?",
    correct_answer: "Blue whale",
    incorrect_answers: ["Elephant", "Giraffe", "Hippopotamus"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "easy",
    question: "What is the capital of Japan?",
    correct_answer: "Tokyo",
    incorrect_answers: ["Kyoto", "Osaka", "Seoul"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "medium",
    question: "What is the chemical formula for water?",
    correct_answer: "H2O",
    incorrect_answers: ["CO2", "O2", "CH4"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "medium",
    question: "Which planet is known as the Red Planet?",
    correct_answer: "Mars",
    incorrect_answers: ["Venus", "Jupiter", "Saturn"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "medium",
    question: "In which year was the first modern Olympic Games held?",
    correct_answer: "1896",
    incorrect_answers: ["1900", "1904", "1920"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "medium",
    question: "What is the currency of Brazil?",
    correct_answer: "Brazilian Real",
    incorrect_answers: ["Peso", "Dollar", "Euro"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "medium",
    question: "What is the chemical formula for oxygen?",
    correct_answer: "O2",
    incorrect_answers: ["CO2", "H2O", "N2"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "hard",
    question: "What is the capital of France?",
    correct_answer: "Paris",
    incorrect_answers: ["Berlin", "London", "Madrid"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "hard",
    question: "What is the largest planet in our solar system?",
    correct_answer: "Jupiter",
    incorrect_answers: ["Earth", "Mars", "Venus"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "hard",
    question: "Which gas do plants absorb from the atmosphere?",
    correct_answer: "Carbon dioxide",
    incorrect_answers: ["Oxygen", "Nitrogen", "Hydrogen"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "hard",
    question: "How many continents are there on Earth?",
    correct_answer: "7",
    incorrect_answers: ["5", "6", "8"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "hard",
    question: "What is the chemical symbol for gold?",
    correct_answer: "Au",
    incorrect_answers: ["Ag", "Cu", "Fe"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "hard",
    question: "What is the freezing point of water in degrees Celsius?",
    correct_answer: "0",
    incorrect_answers: ["-10", "100", "32"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "hard",
    question: "What is the largest mammal in the world?",
    correct_answer: "Blue whale",
    incorrect_answers: ["Elephant", "Giraffe", "Hippopotamus"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "hard",
    question: "What is the capital of Japan?",
    correct_answer: "Tokyo",
    incorrect_answers: ["Kyoto", "Osaka", "Seoul"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question: "This movie contains the quote, 'Nobody puts Baby in a corner.'",
    correct_answer: "Dirty Dancing",
    incorrect_answers: [
      "Three Men and a Baby",
      "Ferris Bueller's Day Off",
      "Pretty in Pink",
    ],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question: "Which Disney animated movie features a character named Simba?",
    correct_answer: "The Lion King",
    incorrect_answers: ["Aladdin", "Mulan", "Beauty and the Beast"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question: "Who played the character of Jack Dawson in the movie Titanic?",
    correct_answer: "Leonardo DiCaprio",
    incorrect_answers: ["Brad Pitt", "Johnny Depp", "Tom Cruise"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the wizard in the Harry Potter series?",
    correct_answer: "Albus Dumbledore",
    incorrect_answers: ["Severus Snape", "Sirius Black", "Remus Lupin"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "easy",
    question: "Who directed the 1994 film 'Pulp Fiction'?",
    correct_answer: "Quentin Tarantino",
    incorrect_answers: [
      "Steven Spielberg",
      "Martin Scorsese",
      "Christopher Nolan",
    ],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "medium",
    question: "Which film won the Academy Award for Best Picture in 2019?",
    correct_answer: "Parasite",
    incorrect_answers: ["Joker", "1917", "Once Upon a Time in Hollywood"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "medium",
    question:
      "Who played the character of Tony Stark in the Marvel Cinematic Universe?",
    correct_answer: "Robert Downey Jr.",
    incorrect_answers: ["Chris Hemsworth", "Chris Evans", "Mark Ruffalo"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "medium",
    question:
      "In the movie 'The Shawshank Redemption,' what is the name of the main character?",
    correct_answer: "Andy Dufresne",
    incorrect_answers: ["Red", "Tommy", "Morgan Freeman"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "medium",
    question: "Who played the character of Jack Dawson in the movie Titanic?",
    correct_answer: "Leonardo DiCaprio",
    incorrect_answers: ["Brad Pitt", "Johnny Depp", "Tom Cruise"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of the wizard in the Harry Potter series?",
    correct_answer: "Albus Dumbledore",
    incorrect_answers: ["Severus Snape", "Sirius Black", "Remus Lupin"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "hard",
    question: "Who directed the 1994 film 'Pulp Fiction'?",
    correct_answer: "Quentin Tarantino",
    incorrect_answers: [
      "Steven Spielberg",
      "Martin Scorsese",
      "Christopher Nolan",
    ],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "hard",
    question: "Which film won the Academy Award for Best Picture in 2019?",
    correct_answer: "Parasite",
    incorrect_answers: ["Joker", "1917", "Once Upon a Time in Hollywood"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "hard",
    question:
      "Who played the character of Tony Stark in the Marvel Cinematic Universe?",
    correct_answer: "Robert Downey Jr.",
    incorrect_answers: ["Chris Hemsworth", "Chris Evans", "Mark Ruffalo"],
  },
  {
    category: "Entertainment: Film",
    type: "multiple",
    difficulty: "hard",
    question:
      "In the movie 'The Shawshank Redemption,' what is the name of the main character?",
    correct_answer: "Andy Dufresne",
    incorrect_answers: ["Red", "Tommy", "Morgan Freeman"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "easy",
    question: "Who is known as the 'King of Pop'?",
    correct_answer: "Michael Jackson",
    incorrect_answers: ["Elvis Presley", "Prince", "Whitney Houston"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "easy",
    question: "Which band released the album 'Rumours' in 1977?",
    correct_answer: "Fleetwood Mac",
    incorrect_answers: ["The Eagles", "Led Zeppelin", "The Rolling Stones"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of Beyoncé's alter ego?",
    correct_answer: "Sasha Fierce",
    incorrect_answers: ["Queen Bey", "Beehive", "Yoncé"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "easy",
    question:
      "Which Beatles album was released in 1967 and is often referred to as 'The White Album'?",
    correct_answer: "The Beatles",
    incorrect_answers: [
      "Abbey Road",
      "Revolver",
      "Sgt. Pepper's Lonely Hearts Club Band",
    ],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "easy",
    question: "Who sang the song 'Shape of You'?",
    correct_answer: "Ed Sheeran",
    incorrect_answers: ["Sam Smith", "Adele", "Justin Bieber"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "medium",
    question: "Which singer released the album 'Lemonade' in 2016?",
    correct_answer: "Beyoncé",
    incorrect_answers: ["Adele", "Rihanna", "Taylor Swift"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "medium",
    question: "Who is the lead singer of the band Coldplay?",
    correct_answer: "Chris Martin",
    incorrect_answers: ["Jonny Buckland", "Guy Berryman", "Will Champion"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of Madonna's debut album?",
    correct_answer: "Madonna",
    incorrect_answers: ["Like a Virgin", "True Blue", "Ray of Light"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "medium",
    question: "Which band released the album 'The Joshua Tree' in 1987?",
    correct_answer: "U2",
    incorrect_answers: ["The Rolling Stones", "The Police", "R.E.M."],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "medium",
    question: "What is the name of Elvis Presley's mansion in Memphis?",
    correct_answer: "Graceland",
    incorrect_answers: ["Neverland", "Highclere Castle", "Buckingham Palace"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "hard",
    question: "Who sang the song 'Bohemian Rhapsody'?",
    correct_answer: "Queen",
    incorrect_answers: ["The Beatles", "Led Zeppelin", "Pink Floyd"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "hard",
    question:
      "Which band released the album 'The Dark Side of the Moon' in 1973?",
    correct_answer: "Pink Floyd",
    incorrect_answers: ["The Rolling Stones", "The Who", "The Doors"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "hard",
    question: "Who is known as the 'Queen of Pop'?",
    correct_answer: "Madonna",
    incorrect_answers: ["Beyoncé", "Rihanna", "Taylor Swift"],
  },
  {
    category: "Entertainment: Music",
    type: "multiple",
    difficulty: "hard",
    question: "Which band released the album 'Abbey Road' in 1969?",
    correct_answer: "The Beatles",
    incorrect_answers: ["Led Zeppelin", "The Rolling Stones", "The Who"],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "easy",
    question: "What does CPU stand for?",
    correct_answer: "Central Processing Unit",
    incorrect_answers: [
      "Computer Personal Unit",
      "Central Process Unit",
      "Computer Processor Unit",
    ],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "easy",
    question: "What is the main function of RAM in a computer?",
    correct_answer: "Temporary data storage",
    incorrect_answers: [
      "Long-term data storage",
      "Processing data",
      "Displaying data",
    ],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "easy",
    question:
      "What is the code name for the mobile operating system developed by Google?",
    correct_answer: "Android",
    incorrect_answers: ["iOS", "Windows", "Blackberry"],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "easy",
    question: "Which programming language is often used for web development?",
    correct_answer: "JavaScript",
    incorrect_answers: ["Python", "Java", "C++"],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "easy",
    question: "What does HTML stand for in web development?",
    correct_answer: "Hypertext Markup Language",
    incorrect_answers: [
      "Hyper Transfer Markup Language",
      "Hypertext Transfer Machine Language",
      "Hypertext Machine Language",
    ],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "medium",
    question: "What does GPU stand for?",
    correct_answer: "Graphics Processing Unit",
    incorrect_answers: [
      "General Processing Unit",
      "Gaming Processing Unit",
      "Graphical Portable Unit",
    ],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "medium",
    question:
      "What is the code name for the open-source web browser developed by Mozilla Corporation?",
    correct_answer: "Firefox",
    incorrect_answers: ["Chrome", "Safari", "Edge"],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "medium",
    question:
      "What is the maximum storage capacity of a standard Blu-ray disc?",
    correct_answer: "50 GB",
    incorrect_answers: ["25 GB", "100 GB", "10 GB"],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which programming language was developed by Sun Microsystems in the 1990s?",
    correct_answer: "Java",
    incorrect_answers: ["Python", "JavaScript", "C++"],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "hard",
    question: "What does BIOS stand for in computing?",
    correct_answer: "Basic Input/Output System",
    incorrect_answers: [
      "Binary Input/Output System",
      "Basic Internal Operating System",
      "Built-In Output System",
    ],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "hard",
    question: "In computing, what does CPU stand for?",
    correct_answer: "Central Processing Unit",
    incorrect_answers: [
      "Computer Personal Unit",
      "Central Process Unit",
      "Computer Processor Unit",
    ],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "hard",
    question: "What is the main function of RAM in a computer?",
    correct_answer: "Temporary data storage",
    incorrect_answers: [
      "Long-term data storage",
      "Processing data",
      "Displaying data",
    ],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "hard",
    question:
      "What is the code name for the mobile operating system developed by Google?",
    correct_answer: "Android",
    incorrect_answers: ["iOS", "Windows", "Blackberry"],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "hard",
    question: "Which programming language is often used for web development?",
    correct_answer: "JavaScript",
    incorrect_answers: ["Python", "Java", "C++"],
  },
  {
    category: "Science: Computers",
    type: "multiple",
    difficulty: "hard",
    question: "What does HTML stand for in web development?",
    correct_answer: "Hypertext Markup Language",
    incorrect_answers: [
      "Hyper Transfer Markup Language",
      "Hypertext Transfer Machine Language",
      "Hypertext Machine Language",
    ],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "easy",
    question:
      "In the game 'Minecraft,' what do you need to mine to collect resources?",
    correct_answer: "Blocks",
    incorrect_answers: ["Coins", "Gems", "Power-ups"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "easy",
    question: "Which video game series features a character named Mario?",
    correct_answer: "Super Mario",
    incorrect_answers: ["Sonic the Hedgehog", "The Legend of Zelda", "Pokemon"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "easy",
    question: "What is the main objective in the game 'Tetris'?",
    correct_answer: "Clear lines",
    incorrect_answers: ["Collect coins", "Defeat enemies", "Solve puzzles"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "easy",
    question: "Which video game series features a character named Link?",
    correct_answer: "The Legend of Zelda",
    incorrect_answers: ["Super Mario", "Sonic the Hedgehog", "Pokemon"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "easy",
    question: "What is the name of the princess in the 'Super Mario' series?",
    correct_answer: "Princess Peach",
    incorrect_answers: [
      "Princess Daisy",
      "Princess Rosalina",
      "Princess Toadstool",
    ],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question: "Which video game series features a character named Solid Snake?",
    correct_answer: "Metal Gear",
    incorrect_answers: ["Call of Duty", "Halo", "Resident Evil"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "In the game 'The Legend of Zelda: Ocarina of Time,' what is the name of the fairy companion?",
    correct_answer: "Navi",
    incorrect_answers: ["Tingle", "Fairy Godmother", "Ness"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "Which video game series features a character named Master Chief?",
    correct_answer: "Halo",
    incorrect_answers: ["Metal Gear", "Call of Duty", "Resident Evil"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "medium",
    question:
      "What is the name of the princess in the 'Legend of Zelda' series?",
    correct_answer: "Princess Zelda",
    incorrect_answers: [
      "Princess Peach",
      "Princess Daisy",
      "Princess Rosalina",
    ],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "hard",
    question: "In the game 'Metal Gear Solid,' who is the main antagonist?",
    correct_answer: "Liquid Snake",
    incorrect_answers: ["Solid Snake", "Big Boss", "Revolver Ocelot"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "hard",
    question:
      "In the game 'The Elder Scrolls V: Skyrim,' what is the name of the player's character?",
    correct_answer: "Dragonborn",
    incorrect_answers: ["Dovahkiin", "Nerevarine", "Hero of Kvatch"],
  },
  {
    category: "Entertainment: Video Games",
    type: "multiple",
    difficulty: "hard",
    question: "Which video game series features a character named Kratos?",
    correct_answer: "God of War",
    incorrect_answers: ["Devil May Cry", "Dark Souls", "Castlevania"],
  },
];
