export const questions = [
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the capital of France?",
    correct_answer: "Paris",
    incorrect_answers: ["Berlin", "Paris", "Madrid", "London"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "medium",
    question: "What is the chemical symbol for water?",
    correct_answer: "H2O",
    incorrect_answers: ["CO2", "H2O", "O2", "H2"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "hard",
    question: "In which year did World War II end?",
    correct_answer: "1945",
    incorrect_answers: ["1939", "1943", "1945", "1941"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "Which country is known as the Land of the Rising Sun?",
    correct_answer: "Japan",
    incorrect_answers: ["Vietnam", "China", "Korea", "Japan"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the largest mammal in the world?",
    correct_answer: "Blue Whale",
    incorrect_answers: ["Hippopotamus", "African Elephant", "Blue Whale", "Giraffe"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "easy",
    question: "What is the chemical symbol for oxygen?",
    correct_answer: "O2",
    incorrect_answers: ["CO2", "O2", "H2O", "O"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "Who was the first President of the United States?",
    correct_answer: "George Washington",
    incorrect_answers: ["John Adams", "Benjamin Franklin", "George Washington", "Thomas Jefferson"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "hard",
    question: "What is the highest mountain in the world?",
    correct_answer: "Mount Everest",
    incorrect_answers: ["K2", "Mount Kilimanjaro", "Mount Everest", "Kangchenjunga"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the largest planet in our solar system?",
    correct_answer: "Jupiter",
    incorrect_answers: ["Saturn", "Venus", "Jupiter", "Mars"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "medium",
    question: "What is the atomic number of carbon?",
    correct_answer: "6",
    incorrect_answers: ["12", "8", "6", "14"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "hard",
    question: "Which famous scientist developed the theory of general relativity?",
    correct_answer: "Albert Einstein",
    incorrect_answers: ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Galileo Galilei"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "Which river is the longest in the world?",
    correct_answer: "Nile",
    incorrect_answers: ["Mississippi", "Yangtze", "Amazon", "Nile"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the largest organ in the human body?",
    correct_answer: "Skin",
    incorrect_answers: ["Heart", "Liver", "Skin", "Brain"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "easy",
    question: "What gas do plants absorb from the atmosphere during photosynthesis?",
    correct_answer: "Carbon Dioxide (CO2)",
    incorrect_answers: ["Carbon Monoxide (CO)", "Oxygen (O2)", "Nitrogen (N2)", "Carbon Dioxide (CO2)"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "Who wrote the Declaration of Independence of the United States?",
    correct_answer: "Thomas Jefferson",
    incorrect_answers: ["John Adams", "George Washington", "Thomas Jefferson", "Benjamin Franklin"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "hard",
    question: "Which desert is the largest in the world?",
    correct_answer: "Sahara Desert",
    incorrect_answers: ["Kalahari Desert", "Arabian Desert", "Sahara Desert", "Gobi Desert"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "How many continents are there in the world?",
    correct_answer: "7",
    incorrect_answers: ["7", "5", "6", "8"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "medium",
    question: "What is the chemical symbol for gold?",
    correct_answer: "Au",
    incorrect_answers: ["Au", "Ag", "Fe", "Cu"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "hard",
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    correct_answer: "Amelia Earhart",
    incorrect_answers: ["Harriet Quimby", "Jacqueline Cochran", "Bessie Coleman", "Amelia Earhart"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "Which country is known as the Land of the Rising Sun?",
    correct_answer: "Japan",
    incorrect_answers: ["Japan", "Korea", "Vietnam", "China"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the smallest prime number?",
    correct_answer: "2",
    incorrect_answers: ["2", "1", "3", "5"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "easy",
    question: "What is the chemical symbol for oxygen?",
    correct_answer: "O2",
    incorrect_answers: ["O", "H2O", "CO2", "O2"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "Which ancient civilization built the pyramids of Giza?",
    correct_answer: "Ancient Egyptians",
    incorrect_answers: ["Ancient Romans", "Ancient Persians", "Ancient Egyptians", "Ancient Greeks"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "hard",
    question: "Which river is the longest in the world?",
    correct_answer: "Nile",
    incorrect_answers: ["Mississippi", "Yangtze", "Amazon", "Nile"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the largest organ in the human body?",
    correct_answer: "Skin",
    incorrect_answers: ["Skin", "Liver", "Brain", "Heart"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "easy",
    question: "What gas do plants absorb from the atmosphere during photosynthesis?",
    correct_answer: "Carbon Dioxide (CO2)",
    incorrect_answers: ["Carbon Dioxide (CO2)", "Carbon Monoxide (CO)", "Oxygen (O2)", "Nitrogen (N2)"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "Who wrote the Declaration of Independence of the United States?",
    correct_answer: "Thomas Jefferson",
    incorrect_answers: ["George Washington", "Benjamin Franklin", "John Adams", "Thomas Jefferson"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "hard",
    question: "Which desert is the largest in the world?",
    correct_answer: "Sahara Desert",
    incorrect_answers: ["Kalahari Desert", "Gobi Desert", "Sahara Desert", "Arabian Desert"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "How many continents are there in the world?",
    correct_answer: "7",
    incorrect_answers: ["6", "5", "7", "8"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "medium",
    question: "What is the chemical symbol for gold?",
    correct_answer: "Au",
    incorrect_answers: ["Cu", "Fe", "Ag", "Au"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "hard",
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    correct_answer: "Amelia Earhart",
    incorrect_answers: ["Jacqueline Cochran", "Amelia Earhart", "Harriet Quimby", "Bessie Coleman"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "Which country is known as the Land of the Rising Sun?",
    correct_answer: "Japan",
    incorrect_answers: ["China", "Korea", "Vietnam", "Japan"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the smallest prime number?",
    correct_answer: "2",
    incorrect_answers: ["3", "5", "2", "1"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "easy",
    question: "What is the chemical symbol for oxygen?",
    correct_answer: "O2",
    incorrect_answers: ["H2O", "CO2", "O", "O2"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "Which ancient civilization built the pyramids of Giza?",
    correct_answer: "Ancient Egyptians",
    incorrect_answers: ["Ancient Romans", "Ancient Greeks", "Ancient Egyptians", "Ancient Persians"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "hard",
    question: "Which river is the longest in the world?",
    correct_answer: "Nile",
    incorrect_answers: ["Yangtze", "Amazon", "Mississippi", "Nile"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the largest organ in the human body?",
    correct_answer: "Skin",
    incorrect_answers: ["Liver", "Heart", "Brain", "Skin"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "easy",
    question: "What gas do plants absorb from the atmosphere during photosynthesis?",
    correct_answer: "Carbon Dioxide (CO2)",
    incorrect_answers: ["Oxygen (O2)", "Carbon Monoxide (CO)", "Carbon Dioxide (CO2)", "Nitrogen (N2)"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "Who wrote the Declaration of Independence of the United States?",
    correct_answer: "Thomas Jefferson",
    incorrect_answers: ["George Washington", "John Adams", "Benjamin Franklin", "Thomas Jefferson"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "hard",
    question: "Which desert is the largest in the world?",
    correct_answer: "Sahara Desert",
    incorrect_answers: ["Gobi Desert", "Sahara Desert", "Kalahari Desert", "Arabian Desert"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "How many continents are there in the world?",
    correct_answer: "7",
    incorrect_answers: ["6", "8", "7", "5"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "medium",
    question: "What is the chemical symbol for gold?",
    correct_answer: "Au",
    incorrect_answers: ["Fe", "Cu", "Au", "Ag"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "hard",
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    correct_answer: "Amelia Earhart",
    incorrect_answers: ["Jacqueline Cochran", "Bessie Coleman", "Harriet Quimby", "Amelia Earhart"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "Which country is known as the Land of the Rising Sun?",
    correct_answer: "Japan",
    incorrect_answers: ["Korea", "Vietnam", "China", "Japan"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "medium",
    question: "What is the smallest prime number?",
    correct_answer: "2",
    incorrect_answers: ["1", "3", "2", "5"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "easy",
    question: "What is the chemical symbol for oxygen?",
    correct_answer: "O2",
    incorrect_answers: ["O", "H2O", "CO2", "O2"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "Which ancient civilization built the pyramids of Giza?",
    correct_answer: "Ancient Egyptians",
    incorrect_answers: ["Ancient Romans", "Ancient Greeks", "Ancient Persians", "Ancient Egyptians"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "hard",
    question: "Which river is the longest in the world?",
    correct_answer: "Nile",
    incorrect_answers: ["Yangtze", "Amazon", "Mississippi", "Nile"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "What is the largest organ in the human body?",
    correct_answer: "Skin",
    incorrect_answers: ["Liver", "Heart", "Skin", "Brain"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "easy",
    question: "What gas do plants absorb from the atmosphere during photosynthesis?",
    correct_answer: "Carbon Dioxide (CO2)",
    incorrect_answers: ["Oxygen (O2)", "Carbon Monoxide (CO)", "Nitrogen (N2)", "Carbon Dioxide (CO2)"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "medium",
    question: "Who wrote the Declaration of Independence of the United States?",
    correct_answer: "Thomas Jefferson",
    incorrect_answers: ["John Adams", "George Washington", "Benjamin Franklin", "Thomas Jefferson"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "hard",
    question: "Which desert is the largest in the world?",
    correct_answer: "Sahara Desert",
    incorrect_answers: ["Kalahari Desert", "Gobi Desert", "Sahara Desert", "Arabian Desert"],
  },
  {
    category: "General Knowledge",
    type: "multiple",
    difficulty: "easy",
    question: "How many continents are there in the world?",
    correct_answer: "7",
    incorrect_answers: ["6", "8", "7", "5"],
  },
  {
    category: "Science",
    type: "multiple",
    difficulty: "medium",
    question: "What is the chemical symbol for gold?",
    correct_answer: "Au",
    incorrect_answers: ["Fe", "Cu", "Au", "Ag"],
  },
  {
    category: "History",
    type: "multiple",
    difficulty: "hard",
    question: "Who was the first woman to fly solo across the Atlantic Ocean?",
    correct_answer: "Amelia Earhart",
    incorrect_answers: ["Jacqueline Cochran", "Bessie Coleman", "Harriet Quimby", "Amelia Earhart"],
  },
  {
    category: "Geography",
    type: "multiple",
    difficulty: "easy",
    question: "Which country is known as the Land of the Rising Sun?",
    correct_answer: "Japan",
    incorrect_answers: ["Korea", "Vietnam", "China", "Japan"],
  },
];

